config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  root to: 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :password

  validates :username, presence: true, uniqueness: true, length: { in: 6..15 }
  validates :password, presence: true, on: :create
  validates :password, confirmation: true, length: { in: 6..20 }, if: :password_present?
  validates :password_confirmation, presence: true, if: :password_present?

  before_save :set_password_digest

  def authenticate(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
  
  private

  def set_password_digest
    return if password.nil? || password_confirmation.nil?
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_present?
    password.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  private

  def authenticate_user!
    if current_user && current_user.locked?
      flash.now[:alert] = t('activerecord.errors.models.user.attributes.locked')
      redirect_to sessions_new_path
    elsif !current_user
      redirect_to sessions_new_path
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  before_action :check_if_already_logged_in, only: :new
  before_action :set_user, only: :create
  
  def new
  end

  def create
    authentication = Authentication::LoginService.new(@user, params[:password]).call()
    @user = authentication.user
    if authentication.success?
      session[:current_user_id] = @user.id
      redirect_to root_path
    else      
      flash[:alert] = authentication.message
      render :new, status: :forbidden
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to sessions_new_path
  end

  private

  

  def user_params
    params.permit(:user).require(:email)
  end
  
  def set_user
    @user||= User.find_by(username: params[:username])
  end
  
  def check_if_already_logged_in
    if current_user
      flash[:notice] = t('alerts.already_logged_in')
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/views/layouts/_header.html.erb
<div class="container">
  <header class="blog-header py-3">
          <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 text-center">
              <% if @current_user %>
                <span class="blog-header-logo text-dark">Welcome <%= @current_user.username %></span>
              <% end %>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
              <% if !@current_user %>
                <a class="p-2 text-dark" href="/sessions/new">Sign in</a>
              <% else %>
                <%= form_tag sessions_destroy_path, method: :delete do %>
                  <%= submit_tag "Sign Out", class: "btn btn-outline-primary" %>
                <% end %>
              <% end %>
            </div>
          </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <div class="container text-center">
        <% flash.each do |type, msg| %>
        <div class="alert alert-danger" role="alert">
          <%= msg %>
        </div>
        <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Root of the application</h1>
  <p class="lead">Only logged in users can access this page</p>
</div>